modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="armacraft"
version="${file.jarVersion}" #mandatory
displayName="ArmaCraft - Reborn" #mandatory
logoFile="assets/armacraft/textures/icon.png"
authors="Threader (Black)"
description='''
Mod próprio do servidor ArmaCraft :D
'''
[[dependencies.examplemod]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armacraft]]
    modId="craftingdead"
    versionRange="[0,)" #mandatory, but any
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.corpse]]
    modId="corpse"
    versionRange="[0,)" #mandatory, but any
    mandatory=true
    ordering="NONE"
    side="BOTH"